Capstone.Web/Models/Card.cs
using System;
using System.Collections.Generic;
using Capstone.Web.DAL;
using System.Configuration;
using System.Linq;
using System.Web;

namespace Capstone.Web.Models
{
    public class Card
    {
        private string connectionString = ConfigurationManager.ConnectionStrings["FlashCardsDB"].ConnectionString;

        public string CardID { get; set; }
        public string Front { get; set; }
        public string Back { get; set; }
        public string UserID { get; set; }
        public string TagName { get; set; }
        /// <summary>
        /// Returns a list of all available Tags.
        /// </summary>
        public List<string> AllTags
        {
            get
            {
                TagsSqlDAL tagSql = new TagsSqlDAL(connectionString);
                return tagSql.TagList;
            }
        }

        /// <summary>
        /// Returns the Tags associated with an individual card in the current instance.
        /// </summary>
        public List<string> ThisCardTags
        {
            get
            {
                TagsSqlDAL tagSql = new TagsSqlDAL(connectionString);
                return tagSql.GetTagsByCardID(CardID);
            }
            set { }

        }

        public List<Deck> DecksHaveThisCard(string userID)
        {
            DeckSqlDAL deckSql = new DeckSqlDAL(connectionString);
            return deckSql.GetDecksByCardID(userID, CardID);
        }

        public List<Deck> AvailableDecksToAddThisCard(string userID)
        {
                DeckSqlDAL deckSql = new DeckSqlDAL(connectionString);
                return deckSql.GetAvailableDecksToAddCard(userID, CardID);
        }

        /// <summary>
        /// Adds a Tag to an individual card in a current instance.
        /// </summary>
        /// <param name="tagName"></param>
        public void AddTagToCard(string tagName)
        {
            TagsSqlDAL tagsSql = new TagsSqlDAL(connectionString);
            tagsSql.AddTagToCard(CardID, tagName);
        }

        public void RemoveTagFromCard(string tagName)
        {
            TagsSqlDAL tagsSql = new TagsSqlDAL(connectionString);
            tagsSql.RemoveTagFromCard(CardID, tagName);
        }
    }
}

Capstone.Web/Controllers/CardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Capstone.Web.DAL;
using Capstone.Web.Models;
using System.Configuration;

namespace Capstone.Web.Controllers
{


    public class CardController : Controller
    {
        private string connectionString = ConfigurationManager.ConnectionStrings["FlashCardsDB"].ConnectionString;
        private CardSqlDAL cDal = new CardSqlDAL(ConfigurationManager.ConnectionStrings["FlashCardsDB"].ConnectionString);
        private DeckSqlDAL dDal = new DeckSqlDAL(ConfigurationManager.ConnectionStrings["FlashCardsDB"].ConnectionString);


        // GET: Card
        public ActionResult Index()
        {
            if (Session["userid"] == null)
            {
                Session["anon"] = "Cards";
                return RedirectToAction("Login", "Home");
            }

            return View();
        }

        //create new card
        public ActionResult CardConstruct()
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            TagsSqlDAL tDal = new TagsSqlDAL(connectionString);
            ViewBag.allTags = tDal.TagDictionary;
            return View("CardCreate");
        }

        //add created card to database
        public ActionResult CardSubmit(Card newCard)
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            cDal.CreateCard(newCard, Session["userid"].ToString());

            List<Card> allCards = cDal.ViewCards(Session["userid"].ToString());

            return View("CardView", allCards);
        }

        //search cards by tag
        public ActionResult CardSearch(string searchString)
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (String.IsNullOrEmpty(searchString))
            {
                return View("Index");
            }
            else
            {
                List<Card> matchingCards = cDal.SearchCard(searchString);

                return View("CardSearch", matchingCards);
            }
        }

        //view all user cards
        public ActionResult CardView()
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            List<Card> allCards = cDal.ViewCards(Session["userid"].ToString());

            return View("CardView", allCards);
        }

        //view all user cards
        public ActionResult CardViewPublic()
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            List<Card> allPublicCards = cDal.ViewAllPublicCards(Session["userid"].ToString());

            return View("CardViewPublic", allPublicCards);
        }

        public ActionResult CardModify(string id)
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            Card existingCard = cDal.GetCardByID(id);
            if (existingCard.UserID != Session["userid"].ToString())
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("CardModify", existingCard);
            }
        }

        public ActionResult CardModifyExpanded(string id)
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            Card existingCard = cDal.GetCardByID(id);
            if (existingCard.UserID != Session["userid"].ToString())
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("CardModifyExpanded", existingCard);
            }
        }

        public ActionResult TagExpand(string id)
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            Card existingCard = cDal.GetCardByID(id);
            if (existingCard.UserID != Session["userid"].ToString())
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("CardModifyExpanded", existingCard);
            }
        }

        public ActionResult TagCollapse(string id)
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            Card existingCard = cDal.GetCardByID(id);
            if (existingCard.UserID != Session["userid"].ToString())
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("CardModify", existingCard);
            }
        }


        //card tags
        [HttpPost]
        public ActionResult AddCardTag(string cardID, string tagName, bool expanded)
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            Card currentCard = cDal.GetCardByID(cardID);
            currentCard.AddTagToCard(tagName);
            if (expanded)
            {
                return RedirectToAction(currentCard.CardID, "Card/CardModifyExpanded");
            }
            return RedirectToAction(currentCard.CardID, "Card/CardModify");
        }

        [HttpPost]
        public ActionResult RemoveCardTag(string cardID, string tagName, bool expanded)
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            Card currentCard = cDal.GetCardByID(cardID);
            currentCard.TagName = tagName;
            currentCard.RemoveTagFromCard(tagName);
            if (expanded)
            {
                return RedirectToAction(currentCard.CardID, "Card/CardModifyExpanded");
            }
            return RedirectToAction(currentCard.CardID, "Card/CardModify");
        }

        [HttpPost]
        public ActionResult CreateCardTag(Card model)
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            Card currentCard = cDal.GetCardByID(model.CardID);

            //if empty input is submitted
            if (model.TagName == null)
            {
                return View("CardModify", currentCard);
            }
            //makes all tags lowercase to avoid conflicts
            model.TagName = model.TagName.ToLower();

            model.AddTagToCard(model.TagName);
            return RedirectToAction(model.CardID, "Card/CardModify");
        }


        public ActionResult CardEditFields(string id, string front, string back, List<string> tags)
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            Card currentCard = new Card();
            currentCard.CardID = id;
            currentCard.Front = front;
            currentCard.Back = back;
            currentCard.ThisCardTags = tags;
 
            cDal.EditCard(currentCard);

            List<Card> allCards = cDal.ViewCards(Session["userid"].ToString());

            return RedirectToAction(currentCard.CardID, "Card/CardModify");
        }


        public ActionResult CardToDeck(string cardID)
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            Card currentCard = cDal.GetCardByID(cardID);
            ViewBag.CardID = cardID;
            ViewBag.CurCard = currentCard;

            string userID = Session["userid"].ToString();

            List<string> PublicUserCardList = cDal.PublicCardUserList;

            List<Deck> allDecks = dDal.GetDecksByUserID(userID);

            if (currentCard.UserID != Session["userid"].ToString() && !PublicUserCardList.Contains(currentCard.UserID))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("CardToDeck", allDecks);
            }
        }

        public ActionResult AddCardToDeck(string cardID, string deckID)
        {
            if (Session["userid"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            dDal.AddCardToDeck(cardID, deckID);

            Card currentCard = cDal.GetCardByID(cardID);
            TempData["addedCard_ID"] = cardID;

            return RedirectToAction("EditDeck", "Deck", new { id = deckID });
        }
    }
}

Capstone.Web/Views/Card/CardCreate.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using Capstone.Web.Models;
@model Card


<h2 class="title">Create a card</h2>

@using (Html.BeginForm("CardSubmit", "Card", new { newCard = Model }, FormMethod.Post))
{
    <div>
        <p>front of card:</p>
        @Html.TextAreaFor(m => m.Front)

        <p>back of card:</p>
        @Html.TextAreaFor(m => m.Back)

    </div>

    <button class="list_item btn">Create card</button>

}

Capstone.Web/Views/Card/CardModify.cshtml
@using Capstone.Web.Models
@using System.Collections.Generic
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    int tagCount = Model.ThisCardTags.Count;
}
@model Card

<script type="text/javascript" src="../../Scripts/CardScripts/card.js"></script>
<div hidden id="tagCount" data-name="@tagCount"></div>



<div class="toprow">
    <div class="row_left">
        <h2 class="modify_header title">Modify card</h2>
    </div>
    <div class="row_right">
        <div>
            @Html.ActionLink("<< Return to cards", "CardView", "Card", new { @class = "list_item row_right btn" })
        </div>
        <div>
            <div class="row_right">All changes saved automatically</div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">

        <div class="col-md-3">
            @using (Html.BeginForm("CardEditFields", "Card", new { id = Model.CardID, front = Model.Front.Trim(), back = Model.Back.Trim(), tags = Model.ThisCardTags }, FormMethod.Get, new { @class = "edit_fields_action" }))
            {
                <div>
                    <h6 class="bold_heading">Front of card:</h6>
                    @Html.TextAreaFor(m => m.Front, new { @id = "front_field", @class = "wide_textarea" })

                    <h6 class="bold_heading">Back of card:</h6>
                    @Html.TextAreaFor(m => m.Back, new { @id = "back_field", @class = "wide_textarea" })
                </div>
            }
        </div>


        <div class="col-md-9">

            <h6 class="bold_heading">Tags:</h6>

            <div class="tag_container">

                <div class="tag_section all_tags">

                    @foreach (string tag in Model.ThisCardTags)
                    {

                        using (Html.BeginForm("RemoveCardTag", "Card", new { cardID = Model.CardID, tagName = tag, expanded = false }, FormMethod.Post, new { @class = "remove_tag_action" }))
                        {
                            <span class="added_tag">@tag</span>
                                @Html.HiddenFor(m => Model.CardID)
                            <span id="@tag" class="x_button remove_tag">&#x2297;</span>
                        }

                    }

                    <p></p>
                    <h6 class="bold_heading">Choose tags to add to your card:</h6>

                    @if (Model.AllTags.Count > 30)
                    {
                        <div class="tag_section limited_tags">

                            @for (int i = 0; i < 30; i++)
                            {
                                string tag = Model.AllTags[i];

                                if (!Model.ThisCardTags.Contains(tag))
                                {
                                    using (Html.BeginForm("AddCardTag", "Card", new { cardID = Model.CardID, tagName = tag, expanded = false }, FormMethod.Post, new { @class = "add_tag_action" }))
                                    {
                                        <span id="@tag" class="add_tag inactive_tag">@tag</span>

                                    }
                                }
                            }
                            <div>
                                @Html.ActionLink("See all >>", "TagExpand", "Card", new { id = Model.CardID }, null)
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="tag_section">

                            @foreach (string tag in Model.AllTags)
                            {
                                if (!Model.ThisCardTags.Contains(tag))
                                {
                                    using (Html.BeginForm("AddCardTag", "Card", new { cardID = Model.CardID, tagName = tag, expanded = false }, FormMethod.Post, new { @class = "add_tag_action" }))
                                    {
                                        <span id="@tag" class="add_tag inactive_tag">@tag</span>

                                    }
                                }
                            }

                        </div>
                    }


                    <h6 class="createtag bold_heading">Create a new tag for your card:</h6>

                    <div class="tag_section">
                        @using (Html.BeginForm("CreateCardTag", "Card", FormMethod.Post))
                        {
                            <input name="TagName" />

                            @Html.HiddenFor(m => Model.CardID)
                            <input type="submit" class="list_item btn" value="Add New Tag">
                        }
                    </div>

                </div>
            </div>
        </div>
    </div>

Capstone.Web/Views/Card/CardModifyExpanded.cshtml
@using Capstone.Web.Models
@using System.Collections.Generic
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    int tagCount = Model.ThisCardTags.Count;
}
@model Card

<script type="text/javascript" src="../../Scripts/CardScripts/card.js"></script>
<div hidden id="tagCount" data-name="@tagCount"></div>



<div class="toprow">
    <div class="row_left">
        <h2 class="modify_header title">Modify card</h2>
    </div>
    <div class="row_right">
        <div>
            @Html.ActionLink("<< Return to cards", "CardView", "Card", new { @class = "list_item row_right btn" })
        </div>
        <div>
            <div class="row_right">All changes saved automatically</div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">

        <div class="col-md-3">
            @using (Html.BeginForm("CardEditFields", "Card", new { id = Model.CardID, front = Model.Front.Trim(), back = Model.Back.Trim(), tags = Model.ThisCardTags }, FormMethod.Get, new { @class = "edit_fields_action" }))
            {
                <div>
                    <h6 class="bold_heading">Front of card:</h6>
                    @Html.TextAreaFor(m => m.Front, new { @id = "front_field", @class = "wide_textarea" })

                    <h6 class="bold_heading">Back of card:</h6>
                    @Html.TextAreaFor(m => m.Back, new { @id = "back_field", @class = "wide_textarea" })
                </div>
            }
        </div>


        <div class="col-md-9">

            <h6 class="bold_heading">Tags:</h6>

            <div class="tag_container">

                <div class="tag_section all_tags">

                    @foreach (string tag in Model.ThisCardTags)
                    {

                        using (Html.BeginForm("RemoveCardTag", "Card", new { cardID = Model.CardID, tagName = tag, expanded = true }, FormMethod.Post, new { @class = "remove_tag_action" }))
                        {
                            <span class="added_tag">@tag</span>
                            @Html.HiddenFor(m => Model.CardID)
                            <span id="@tag" class="x_button remove_tag">&#x2297;</span>
                        }

                    }

                    <p></p>
                    <h6 class="bold_heading">Choose tags to add to your card:</h6>

                    <div class="tag_section">
                        @foreach (string tag in Model.AllTags)
                        {
                            if (!Model.ThisCardTags.Contains(tag))
                            {
                                using (Html.BeginForm("AddCardTag", "Card", new { cardID = Model.CardID, tagName = tag, expanded = true }, FormMethod.Post, new { @class = "add_tag_action" }))
                                {
                                    <span id="@tag" class="add_tag inactive_tag">@tag</span>

                                }
                            }
                        }
                        <div>
                            @Html.ActionLink("^^ See less", "TagCollapse", "Card", new { id = Model.CardID }, null)
                        </div>
                    </div>


                    <h6 class="createtag bold_heading">Create a new tag for your card:</h6>

                    <div class="tag_section">
                        @using (Html.BeginForm("CreateCardTag", "Card", FormMethod.Post))
                        {
                            <input name="TagName" />

                            @Html.HiddenFor(m => Model.CardID)
                            <input type="submit" class="list_item btn" value="Add New Tag">
                        }
                    </div>

                </div>
            </div>
        </div>
    </div>

Capstone.Web/Views/Card/CardSearch.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using Capstone.Web.Models
@model List<Card>

<h2 class="title">Card search results</h2>


@{
    if (Model.Count == 0)
    {
        <p>No cards found with that tag.</p>
        <p class="noresults_option">@Html.ActionLink("View all cards", "CardView", "Card")</p>
        <p class="noresults_option">@Html.ActionLink("Create a new card", "CardConstruct", "Card")</p>
    }
    else
    {
        <div class="card_flex_container">

           
                @foreach (Card thisCard in Model)
                 {

                    <div class="card_bothsides">
                        <div class="card_front">@thisCard.Front</div>
                        <div class="card_back">@thisCard.Back</div>
                        <div class="card_option">
                            @Html.ActionLink("Add card to deck", "CardToDeck", "Card")
                        </div>
                        <div>
                            @Html.ActionLink("Modify this card", "CardModify", "Card", new { id = thisCard.CardID }, null)
                        </div>
                    </div>
                 }

        </div>
    }
}

Capstone.Web/Views/Card/CardToDeck.cshtml
@using Capstone.Web.Models
@model List<Deck>
@{
    ViewBag.Title = "SelectDeck";
    List<Deck> availableDecks = ViewBag.CurCard.AvailableDecksToAddThisCard(Session["userid"].ToString());
    List<Deck> decksWithCard = ViewBag.CurCard.DecksHaveThisCard(Session["userid"].ToString());
}

@{
    <h2 class="title">Add card to deck:</h2>
    if (availableDecks.Count > 0)
    {
        foreach (Deck thisDeck in availableDecks)
        {
            <li class="deck_list">
                @Html.ActionLink(thisDeck.Name, "AddCardToDeck", new { cardID = ViewBag.CardID, deckID = thisDeck.DeckID })
            </li>
        }
    }

    if (Model.Count == 0)
    {
        <p class="deck_list">
            You don't have any decks yet.
            <br />
            @Html.ActionLink("Create one here!", "AddDeck", "Deck", null, new { @class = "create_link" })
        </p>
    }

    <hr />

    if (decksWithCard.Count > 0)
    {
        <h5>Your card is currently in these decks:</h5>
        foreach (Deck thisDeck in decksWithCard)
        {
            <li>
                @Html.Label(thisDeck.Name)
            </li>
        }
    }

}

Capstone.Web/Views/Card/CardView.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using Capstone.Web.Models
@model List<Card>

<h2 class="title">All your cards</h2>

<div class="card_flex_container">

    @{
        if (Model.Count == 0)
        {
            <p>
                You don't have any cards yet.
                @Html.ActionLink("Create some here!", "CardConstruct", "Card", null, new { @class = "inline_link" })
            </p>
        }
        foreach (Card thisCard in Model)
        {

            <div class="card_bothsides">
                <div class="card_front">@thisCard.Front</div>
                <div class="card_back">@thisCard.Back</div>
                <div class="card_tags">
                    @{
                        //cap the number of tags to display in this view at 7
                        if (thisCard.ThisCardTags.Count > 7)
                        {
                            for (int i = 0; i < 7; i++)
                            {
                                string tag = thisCard.ThisCardTags[i];
                                <span class="added_tag">@tag</span>
                            }
                            <span>...</span>
                        }
                        else
                        {
                            foreach (string tag in thisCard.ThisCardTags)
                            {
                                <span class="added_tag">@tag</span>
                            }
                        }
                    }
                </div>

                <div class="card_options">

                        @Html.ActionLink("Add to deck", "CardToDeck", "Card", new { cardID = thisCard.CardID }, new { @class = "float-left list_item btn" })

                        @Html.ActionLink("Modify", "CardModify", "Card", new { id = thisCard.CardID }, new { @class = "float-right list_item btn" })

                </div>

            </div>


        }
    }

</div>

Capstone.Web/Views/Card/CardViewPublic.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using Capstone.Web.Models
@model List<Card>

<h2 class="title">All public cards</h2>

<div class="card_flex_container">

    @{
        if (Model.Count == 0)
        {
            <p>
                You don't have any cards yet.
                @Html.ActionLink("Create some here.", "CardConstruct", "Card")
            </p>
        }
        foreach (Card thisCard in Model)
        {

            <div class="card_bothsides">
                <div class="card_front">@thisCard.Front</div>
                <div class="card_back">@thisCard.Back</div>
                <div class="card_tags">
                    @{
                        //cap the number of tags to display in this view at 7
                        if (thisCard.ThisCardTags.Count > 7)
                        {
                            for (int i = 0; i < 7; i++)
                            {
                                string tag = thisCard.ThisCardTags[i];
                                <span class="added_tag">@tag</span>
                            }
                            <span>...</span>
                        }
                        else
                        {
                            foreach (string tag in thisCard.ThisCardTags)
                            {
                                <span class="added_tag">@tag</span>
                            }
                        }
                    }
                </div>

                <div class="card_options">
                    <button class="list_item btn float-left">
                        @Html.ActionLink("Add to deck", "CardToDeck", "Card", new { cardID = thisCard.CardID }, null)
                    </button>
                </div>

            </div>


        }
    }

Capstone.Web/Views/Card/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2 class="title">Cards</h2>

<div class="container-fluid">

    <div class="row">

        <div class="col-sm-4">
            <div class="index_option">
                @Html.ActionLink("Create a Card", "CardConstruct", "Card")
            </div>
        </div>

        <div class="col-sm-4">
            <div class="index_option">
                @Html.ActionLink("View My Cards", "CardView", "Card")
            </div>
        </div>

        <div class="col-sm-4">
            <div class="index_option">
                @Html.ActionLink("View All Public Cards", "CardViewPublic", "Card")
            </div>
        </div>

    </div>

    <div class="index_option">
        @using (Html.BeginForm("CardSearch", "Card", FormMethod.Get))
        {
            <span>
                @Html.TextBox("SearchString")
            </span>
            
            <button type="submit" class="list_item btn">Search by Tag</button>
        }
    </div>

</div>